### ISSUE TITLE
Pduino 0.7 compatibility with Pd vanilla

### ISSUE THREAD

**Issue by marivagil** [reduzent/pduino#3]
Problem description : although sending message "pinMode 7 input" to the [arduino] object, reading the #7 input state is impossible. There is no error message, just nothing happens.

Config :
- OSX HighSierra 10.13.6
- Pduino 0.7
- Pd 0.51.1
- Arduino Nano Atmel 168
- firmware AllInputsFirmata.ino 2 5
Tested too with :
- Arduino Nano Atmel 368
- firmware StandardFirmata.ino 2 5

Works fine with Max/MSP's [arduino] object.

**Comment by reduzent** [comment]
Thanks for the report. I have access to a Arduino Leonardo and I can confirm that pin 7 when set as input does not report anything.
